adding first nav bar to details page
GSG-G11/Team3-News pull request #24
Opened 2022-02-01 22:00 UTC by Mahmoud-Ahmad2

2022-02-01 22:06 UTC, IsraaHamdi requested changes
delete selector .title from details.css file

2022-02-02 05:08 UTC, rawaneyad approved these changes

2022-02-02 08:29 UTC, IsraaHamdi approved these changes

2022-02-02 08:30 UTC, amasri88 approved these changes

2022-02-02 08:30 UTC, merged